#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform image2D resultImage;

void main() {
    vec3 rgb = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy)).rgb;

    vec4 resolution = vec4(vec3(rgb), 1.0);

    for (int i = 0; i < 1; i++) {
        for (int j = 0; j < 1; j++) {
            imageStore(resultImage, ivec2(gl_GlobalInvocationID.x + i, gl_GlobalInvocationID.y + j), resolution);
        }
    }
}